### ISSUE TITLE
Probar tambien que la function alert se haya llamado pasandole el id del thetitle

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/dom-exercises#5]
Fijate que aqui estas comprobando que alert se haya llamado por lo menos una vez.

https://github.com/4GeeksAcademy/dom-exercises/blob/fba932a1cf2c3dc97fceee2068161815e0d2b1bd/exercises/02-Select-DOM-Element/tests.js#L28

Pero tambien tienes que probar que cuando se llamo se le halla pasado `theTitle` como parametro que es el ID del elemento del DOM, algo asi:
```js
expect(alert).toHaveBeenCalledWith("theTitle");
```

**Comment by alesanchezr** [comment]
@ljavierrodriguez revisa esto, creo que todos los ejercicios necesitan revisar las pruebas que les hiciste

**Comment by ljavierrodriguez** [comment]
ready
